volumes:
  backend-python-packages:
  worker-python-packages:

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend/app:/app
      - backend-python-packages:/app/.venv
    ports:
      - "8080:8080"
    depends_on:
      - localstack
    networks:
      - app-network

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes:
      - ./worker/app:/app
      - worker-python-packages:/app/.venv
    ports:
      - "8081:8080"
    depends_on:
      - localstack
    networks:
      - app-network

  localstack:
    image: localstack/localstack:latest
    container_name: localstack_main
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs,dynamodb,lambda
      - DEBUG=1
      - AWS_DEFAULT_REGION=ap-northeast-1
      - DOCKER_HOST=unix:///var/run/docker.sock
      # 【重要】LambdaコンテナをこのComposeのネットワークに参加させる
      - LAMBDA_DOCKER_NETWORK=app-network
    volumes:
      # Docker in Docker (Lambda起動用)
      - "/var/run/docker.sock:/var/run/docker.sock"
      # 初期化スクリプト
      - "./init_aws.sh:/etc/localstack/init/ready.d/init_aws.sh"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    name: app-network
