volumes:
  fastapijobquetemplate-sqs-python-packages:

services:
  fastapijobquetemplate-sqs:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./app:/app
      - fastapijobquetemplate-sqs-python-packages:/app/.venv
    ports:
      - "8080:8080"
    environment:
      - AWS_ENDPOINT_URL=http://localstack:4566
      - AWS_DEFAULT_REGION=ap-northeast-1
      - TABLE_NAME=Jobs
      - QUEUE_NAME=job-queue
    depends_on:
      - localstack
    networks:
      - app-network

  localstack:
    image: localstack/localstack:latest
    container_name: localstack_main
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs,dynamodb,lambda
      - DEBUG=1
      - AWS_DEFAULT_REGION=ap-northeast-1
      - DOCKER_HOST=unix:///var/run/docker.sock
      # Lambda起動時にホストの ./app を /var/task にマウントする
      - LAMBDA_DOCKER_FLAGS=-v ${PWD}/app:/var/task
    volumes:
      # Docker in Docker (Lambdaコンテナ起動用)
      - "/var/run/docker.sock:/var/run/docker.sock"
      # 初期化スクリプト
      - "./init_aws.sh:/etc/localstack/init/ready.d/init_aws.sh"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
